export const browserCoreExamples = [
  "nemo browser status",
  "nemo browser start",
  "nemo browser stop",
  "nemo browser tabs",
  "nemo browser open https://example.com",
  "nemo browser focus abcd1234",
  "nemo browser close abcd1234",
  "nemo browser screenshot",
  "nemo browser screenshot --full-page",
  "nemo browser screenshot --ref 12",
  "nemo browser snapshot",
  "nemo browser snapshot --format aria --limit 200",
  "nemo browser snapshot --efficient",
  "nemo browser snapshot --labels",
];

export const browserActionExamples = [
  "nemo browser navigate https://example.com",
  "nemo browser resize 1280 720",
  "nemo browser click 12 --double",
  'nemo browser type 23 "hello" --submit',
  "nemo browser press Enter",
  "nemo browser hover 44",
  "nemo browser drag 10 11",
  "nemo browser select 9 OptionA OptionB",
  "nemo browser upload /tmp/file.pdf",
  'nemo browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "nemo browser dialog --accept",
  'nemo browser wait --text "Done"',
  "nemo browser evaluate --fn '(el) => el.textContent' --ref 7",
  "nemo browser console --level error",
  "nemo browser pdf",
];
