#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${NEMO_INSTALL_E2E_IMAGE:-${NEMO_INSTALL_E2E_IMAGE:-nemo-install-e2e:local}}"
INSTALL_URL="${NEMO_INSTALL_URL:-${NEMO_INSTALL_URL:-https://nemo.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
NEMO_E2E_MODELS="${NEMO_E2E_MODELS:-${NEMO_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e NEMO_INSTALL_URL="$INSTALL_URL" \
  -e NEMO_INSTALL_TAG="${NEMO_INSTALL_TAG:-${NEMO_INSTALL_TAG:-latest}}" \
  -e NEMO_E2E_MODELS="$NEMO_E2E_MODELS" \
  -e NEMO_INSTALL_E2E_PREVIOUS="${NEMO_INSTALL_E2E_PREVIOUS:-${NEMO_INSTALL_E2E_PREVIOUS:-}}" \
  -e NEMO_INSTALL_E2E_SKIP_PREVIOUS="${NEMO_INSTALL_E2E_SKIP_PREVIOUS:-${NEMO_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
